### ISSUE TITLE
/snap/frame-it/18/frame-it: line 21: ubuntu-frame_beta: command not found

### ISSUE THREAD

**Issue by claskfosmic** [AlanGriffiths/frame-it#5]
Followed the instructions on [https://mir-server.io/docs/make-a-secure-ubuntu-web-kiosk](https://mir-server.io/docs/make-a-secure-ubuntu-web-kiosk) and [https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame](https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame) in order to convert a default Ubuntu Server Minimal installation (_Ubuntu 22.04.4 LTS_) with the desktop installed (using `sudo apt-get install --no-install-recommends ubuntu-desktop`) into a kiosk, dislaying a webpage.

I've used the following commands to do so:

```
sudo snap install ubuntu-frame
sudo snap install wpe-webkit-mir-kiosk
sudo snap set ubuntu-frame daemon=true
sudo snap set wpe-webkit-mir-kiosk daemon=true
sudo snap connect wpe-webkit-mir-kiosk:wayland
sudo snap connect ubuntu-frame:login-session-control
sudo snap set wpe-webkit-mir-kiosk url=https://ubuntu.com
sudo snap start wpe-webkit-mir-kiosk
```

So far, this works perfectly, but I'm trying to install and configure VNC onto it in order to remotely login onto the display in order to view what the user will see, so used the commands below:

```
sudo snap install ubuntu-frame-vnc
sudo snap set ubuntu-frame-vnc daemon=true
/snap/ubuntu-frame-vnc/current/bin/setup.sh
```

From there, i tried to install and run frame-it in order to allow/enable remote access, by using these commands

```
sudo snap install --classic frame-it
sudo snap set frame-it shell-app=wpe-webkit-mir-kiosk.cog
```

When calling `frame-it wpe-webkit-mir-kiosk`, I get the following error "**/snap/frame-it/18/frame-it: line 21: ubuntu-frame_beta: command not found**". 

Continued by executing `frame-it.check`, which gives me the following response:

```
~$ frame-it.check

Checking: ubuntu-frame_beta installation (needed for all commands)
 WARNING: ubuntu-frame_beta NOT installed. Please run the following:
  sudo snap install ubuntu-frame_beta
Checking: ubuntu-frame_beta has login-session-control (needed to run a login shell)
error: snap "ubuntu-frame_beta" not found
 WARNING: ubuntu-frame_beta:login-session-control NOT connected. Please run the following:
  sudo snap connect ubuntu-frame_beta:login-session-control
Checking: shell-app option (needed for frame-it.shell and to run a login shell)
 . OK . : shell-app is set (to 'wpe-webkit-mir-kiosk.cog') and can be found
Checking: osk option
 . OK . : "osk" is unset
Checking: vnc-viewer option (needed for frame-it.vnc)
 . OK . : vnc-viewer is set (to 'gvncviewer') and can be found
```

Executing `sudo snap connect ubuntu-frame_beta:login-session-control`

When I call `frame-it.shell`, the same error (**/snap/frame-it/18/frame-it: line 21: ubuntu-frame_beta: command not found**) appears. The application continues, but I'm unable to connect using RealVNC Viewer. How can is solve this issue?

**Comment by claskfosmic** [comment]
Got a little further with a fresh/clean installation and the steps described above. After installing gvncviewer with `sudo apt-get install gvncviewer`, executing `frame-it.check`, which gives me the following response:

```
~$ frame-it.check

Checking: Ubuntu Frame installation (needed for all commands)
 . OK . : Ubuntu Frame is installed
Checking: Ubuntu Frame has login-session-control (needed to run a login shell)
 . OK . : ubuntu-frame:login-session-control is connected
Checking: shell-app option (needed for frame-it.shell and to run a login shell)
 . OK . : shell-app is set (to 'wpe-webkit-mir-kiosk.cog') and can be found
Checking: osk option
 . OK . : "osk" is unset
Checking: vnc-viewer option (needed for frame-it.vnc)
 . OK . : vnc-viewer is set (to 'gvncviewer') and can be found
 ```

When I run `frame-it.shell`, I get the response and errors below:

```
~$ frame-it.shell

+ [ /snap/ubuntu-frame/8587/bin/run-frame = --help ]
+ mkdir -p /root/snap/ubuntu-frame/8587/.config/
+ grep -vE (^vt=|^console-provider=vt) /var/snap/ubuntu-frame/8587/frame.config
+ rm -f /root/snap/ubuntu-frame/8587/.config/frame.display
+ cp /var/snap/ubuntu-frame/8587/frame.display /root/snap/ubuntu-frame/8587/.config/
+ exec /snap/ubuntu-frame/8587/bin/run-frame /snap/ubuntu-frame/8587/bin/graphics-core22-wrapper /snap/ubuntu-frame/8587/usr/local/bin/frame
+ [ /snap/ubuntu-frame/8587/bin/graphics-core22-wrapper = --help ]
+ dirname /run/user/0/snap.ubuntu-frame
+ XDG_RUNTIME_DIR=/run/user/0
+ export XDG_RUNTIME_DIR
+ mkdir -p /run/user/0 -m 700
+ [ -n wayland-0 ]
+ [ -e /run/user/0/wayland-0 ]
+ unset WAYLAND_DISPLAY
+ exec /snap/ubuntu-frame/8587/bin/graphics-core22-wrapper /snap/ubuntu-frame/8587/usr/local/bin/frame
[2024-03-19 09:19:41.526216] < - debug - > miral: Loaded display configuration file: /root/snap/ubuntu-frame/8587/.config/frame.display
[2024-03-19 09:19:41.556321] <information> mirserver: Starting
[2024-03-19 09:19:41.577238] < - debug - > mirserver: Not using logind for session management: Seat has no active session
[2024-03-19 09:19:41.578196] < - debug - > mirserver: Using Linux VT subsystem for session management
[2024-03-19 09:19:41.578690] <information> mircommon: Loading modules from: /snap/ubuntu-frame/8587/usr/lib/x86_64-linux-gnu/mir/server-platform
[2024-03-19 09:19:41.578882] <information> mircommon: Loading module: /snap/ubuntu-frame/8587/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-eglstream-kms.so.21
[2024-03-19 09:19:41.578974] <information> mircommon: Loading module: /snap/ubuntu-frame/8587/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-gbm-kms.so.21
[2024-03-19 09:19:41.579019] <information> mircommon: Loading module: /snap/ubuntu-frame/8587/usr/lib/x86_64-linux-gnu/mir/server-platform/renderer-egl-generic.so.21
[2024-03-19 09:19:41.579067] <information> mircommon: Loading module: /snap/ubuntu-frame/8587/usr/lib/x86_64-linux-gnu/mir/server-platform/server-x11.so.21
[2024-03-19 09:19:41.579108] <information> mircommon: Loading module: /snap/ubuntu-frame/8587/usr/lib/x86_64-linux-gnu/mir/server-platform/input-evdev.so.8
[2024-03-19 09:19:41.581794] <information> mirserver: Found display driver: mir:eglstream-kms (version 2.16.3)
[2024-03-19 09:19:41.587123] < - debug - > eglstream: Found EGLDeviceEXT with device extensions: EGL_EXT_device_drm EGL_EXT_device_drm_render_node
[2024-03-19 09:19:41.587633] <information> eglstream: Failed to query DRM node for EGLDevice: Failed to claim DRM master: Device or resource busy
[2024-03-19 09:19:41.587731] < - debug - > eglstream: Found EGLDeviceEXT with device extensions: EGL_MESA_device_software EGL_EXT_device_drm_render_node
[2024-03-19 09:19:41.587856] <information> eglstream: Failed to query DRM node for EGLDevice: Failed to determine DRM device node path from EGLDevice: EGL_BAD_PARAMETER (0x300c)
[2024-03-19 09:19:41.587890] < - debug - > eglstream: EGLDeviceEXTs found, but none are suitable for Mir
[2024-03-19 09:19:41.587927] <information> mirserver: (Unsupported by system environment)
[2024-03-19 09:19:41.587971] <information> mirserver: Found display driver: mir:gbm-kms (version 2.16.3)
[2024-03-19 09:19:41.592024] < - debug - > gbm-kms: Quirks: checking device with devnode: /dev/dri/card0, driver i915
[2024-03-19 09:19:41.592488] <information> gbm-kms: Failed to probe DRM device: ./src/server/console/linux_virtual_terminal.cpp(167): Throw in function {anonymous}::DRMDevice::DRMDevice(mir::VTFileOperations&, const char*, std::unique_ptr<mir::Device::Observer>, const std::shared_ptr<mir::LinuxVirtualTerminal::DeviceList>&)
Dynamic exception type: boost::wrapexcept<boost::exception_detail::error_info_injector<std::system_error> >
std::exception::what: Failed to claim DRM master: Device or resource busy
[boost::errinfo_file_name_*] = /dev/dri/card0

[2024-03-19 09:19:41.592992] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
[2024-03-19 09:19:41.593426] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
[2024-03-19 09:19:41.593864] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
[2024-03-19 09:19:41.594303] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
[2024-03-19 09:19:41.594731] < - debug - > gbm-kms: Quirks: checking device with devnode: (null), driver 
[2024-03-19 09:19:41.594855] <information> mirserver: (Unsupported by system environment)
[2024-03-19 09:19:41.594909] <information> mirserver: Found display driver: mir:egl-generic (version 2.16.3)
[2024-03-19 09:19:41.595015] <information> mirserver: Found display driver: mir:x11 (version 2.16.3)
[2024-03-19 09:19:41.595090] <information> mirserver: (Unsupported by system environment)
ERROR: ./src/server/graphics/default_configuration.cpp(253): Throw in function virtual const std::vector<std::shared_ptr<mir::graphics::DisplayPlatform> >& mir::DefaultServerConfiguration::the_display_platforms()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: Exception while creating graphics platform
ERROR: ./src/server/graphics/platform_probe.cpp(184): Throw in function std::vector<std::pair<mir::graphics::SupportedDevice, std::shared_ptr<mir::SharedLibrary> > > {anonymous}::modules_for_device(const std::function<std::vector<mir::graphics::SupportedDevice>(const mir::SharedLibrary&)>&, const std::vector<std::shared_ptr<mir::SharedLibrary> >&)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: Failed to find any platforms for current system
```

**Comment by AlanGriffiths** [comment]
> From there, i tried to install and run frame-it in order to allow/enable remote access, by using these commands
> 
> ```
> sudo snap install --classic frame-it
> sudo snap set frame-it shell-app=wpe-webkit-mir-kiosk.cog
> ```

The reason `frame-it` is mentioned is that it provides a handy script (`frame-it.vnc`) for the _client_ machine to connect to the VNC host. To do this:

1. `frame-it` needs to be installed on the client
2. There is no need to set the `shell-app`

> When calling `frame-it wpe-webkit-mir-kiosk`, I get the following error "**/snap/frame-it/18/frame-it: line 21: ubuntu-frame_beta: command not found**".

There is also no need to set `shell` (especially not to "ubuntu-frame_beta" - that is used as an example of how to test parallel installs of `ubuntu-frame`) it is also irrelevant to your use case.

> Continued by executing `frame-it.check`, which gives me the following response:
> 
> ```
> ~$ frame-it.check
> Checking: ubuntu-frame_beta installation (needed for all commands)
>  WARNING: ubuntu-frame_beta NOT installed. Please run the following:
>   sudo snap install ubuntu-frame_beta
> Checking: ubuntu-frame_beta has login-session-control (needed to run a login shell)
> error: snap "ubuntu-frame_beta" not found
>  WARNING: ubuntu-frame_beta:login-session-control NOT connected. Please run the following:
>   sudo snap connect ubuntu-frame_beta:login-session-control
> Checking: shell-app option (needed for frame-it.shell and to run a login shell)
>  . OK . : shell-app is set (to 'wpe-webkit-mir-kiosk.cog') and can be found
> Checking: osk option
>  . OK . : "osk" is unset
> Checking: vnc-viewer option (needed for frame-it.vnc)
>  . OK . : vnc-viewer is set (to 'gvncviewer') and can be found
> ```
> 
> Executing `sudo snap connect ubuntu-frame_beta:login-session-control`
> 
> When I call `frame-it.shell`, the same error (**/snap/frame-it/18/frame-it: line 21: ubuntu-frame_beta: command not found**) appears. The application continues, but I'm unable to connect using RealVNC Viewer. How can is solve this issue?

This also relates to a different usecase (and the error is because you have set set `shell=ubuntu-frame_beta`.

**Comment by AlanGriffiths** [comment]
https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame

**Comment by claskfosmic** [comment]
> https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame

Hi Alan,

Thans for your reply. I've found and followed the instructions on this URL. At the end, it says "It is up to the operator to expose it securely to the outside or provide other means of access. SSH port forwarding is a common approach: Here is one [example](https://github.com/AlanGriffiths/frame-it/blob/master/frame-it/frame-it-vnc) using the frame-it snap and gvncviewer", which lead me here. It was never clear to me that this was about the client.

On the URL you mentioned, it says the it was tested with RealVNC, but when I try to connect, it tels me "the connection was refused by the computer". When I use `sudo ss -tlnp | grep 5900`, I find out that wayvnc is using 127.0.0.1:5900 as address and port.

```
LISTEN 0      16         127.0.0.1:5900      0.0.0.0:*    users:(("wayvnc",pid=1122,fd=13))        
```

Also `ps aux | grep "wayvnc"` tells me wayvnc is running using localhost:

```
root        1122  0.0  1.6 239524 63264 ?        Ssl  08:47   0:02 /snap/ubuntu-frame-vnc/325/usr/local/bin/wayvnc --gpu localhost 5900
```

There is no iptables or ufw active, however, I'm unable to find any helpful instructions, how to "expose it to the outside"... Ubuntu Frame looks like a good solution, but setting it up is still quite a challenge I'm trying to figure out how to connect to the Ubuntu Frame / Wayland using RealVNC (from my Windows PC), but really struggling how configure this.

**Comment by AlanGriffiths** [comment]
The frame-it.vnc script sets up the ssh tunnelling (assuming the current user has ssh credentials) and then runs a VNC client.

Here's the script: https://github.com/AlanGriffiths/frame-it/blob/master/frame-it/frame-it-vnc

This defaults to `vnc-viewer=gvncviewer`, but that can be set to other commands.

**Comment by claskfosmic** [comment]
> Here's the script: https://github.com/AlanGriffiths/frame-it/blob/master/frame-it/frame-it-vnc

How to get this script to work, using RealVNC from any Windows PC in order to connect. I just want to open RealVNC on my PC, insert the IP-address of the Ubuntu system and connect to it. Are there any options to run ubuntu-frame-vnc without binding it to 127.0.0.1/localhost, but using 0.0.0.0 instead?

And if not, how to connect to the Ubuntu Frame VNC environment using Real VNC from a Windows PC? The frame-it-vnc script won't work on Mac/Windows. How to configure this?

**Comment by AlanGriffiths** [comment]
I have no experience of RealVNC on Windows, you are the expert on that.

As it says in [How to use remote assistance with Ubuntu Frame](https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame) "Rather than expose an extra attack surface, ubuntu-frame-vnc is configured to only listen on localhost, on port 5900 (the default VNC port). It is up to the operator to expose it securely to the outside or provide other means of access."

The `frame-it.vnc` script is one way to do this and uses `ssh` tunnelling to provide secure access from the client system. I chose that because ssh is the normal way to access Ubuntu Core remotely.

I'm fairly sure I used ssh on Windows (but that was last millennium) so this approach should be possible on Windows too. But I don't remember what tools I used, nor how to configure them.

**Comment by Saviq** [comment]
@claskfosmic we don't expose VNC outside of localhost because there's just no reliable way to secure it.

A simple `ssh -L 5900:localhost:5900 <user>@<remote>` should allow you to connect with RealVNC on `localhost`.

I'm adding that to the documentation at https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame?trk=public_post_comment-text#heading--remote-access
